#!/usr/bin/env python3
"""brando marklib tokens — Theme -> CSS custom properties, once.

The projection from a `meridian.theme.v1.Theme` onto CSS custom properties is
written three times in the fleet, by three people, with three fallback tables:

    meridian-playground/src/theme.ts   skinVars()      -> --bg / --surface / ...
    meridian-mui-kit/src/theme.ts      (to MUI)        -> a FALLBACK block
    brando mdbook/templates/custom.css.tmpl            -> --fv-* (hardcoded)

Three copies of one mapping is how `savvi-skin.ts` came to still ship MUI's
`#1976d2` long after `skins/savvi.textpb` replaced it with the real brandbook
`#00ADEF`: the theme moved and the copies did not. A projection with no single
owner is a palette with no single source.

This module is the owner. It reads the SAME `<brand>.json` the renderers read --
the artifact `skin_json` derives from the validated binpb -- so there is no third
representation of the palette anywhere in the chain.

PREFIX. Meridian's own renderers read `--mer-*`; brando's mdBook theme historically
read `--fv-*`, which put fastverk's name in every other brand's stylesheet. Neither
is a good default for a brand-neutral tool, so the prefix is a parameter and the
default is the neutral `--brand-*`. Pass `prefix="mer"` for a stylesheet a meridian
renderer will consume.
"""
from __future__ import annotations

import json
from typing import Optional

# The palette roles in meridian.theme.v1.Palette, in field order. Roles absent
# from a given skin are simply not emitted -- a renderer's own fallback then
# applies, which is the behaviour every consumer already expects.
PALETTE_ROLES = (
    "bg", "surface", "fg", "muted", "border",
    "accent", "accent_strong", "on_accent",
    "danger", "success", "code_bg", "code_fg",
    # Present in meridian_schemas >= 0.20.0 only. Emitted when a skin has them so
    # this does not need touching when that release finally lands; see
    # skins/testdata/fixture.textpb for why no skin can set them today.
    "warning", "info",
)

TYPOGRAPHY_TOKENS = (
    ("sans", "sans"),
    ("mono", "mono"),
    ("display", "display"),
    ("heading_tracking", "heading-tracking"),
)

TYPOGRAPHY_PX = (("base_size_px", "base-size"),)
TYPOGRAPHY_NUM = (("heading_weight", "heading-weight"), ("body_weight", "body-weight"))
METRICS_PX = (("radius_px", "radius"), ("unit_px", "unit"))


def _var(prefix: str, name: str) -> str:
    return "--%s-%s" % (prefix, name.replace("_", "-"))


def _palette_block(palette: dict, prefix: str, indent: str = "  ") -> list:
    return [
        "%s%s: %s;" % (indent, _var(prefix, role), palette[role])
        for role in PALETTE_ROLES
        if palette.get(role)
    ]


def _shared_block(theme: dict, prefix: str, indent: str = "  ") -> list:
    """Typography + metrics — the tokens that do not vary by light/dark."""
    out = []
    typo = theme.get("typography") or {}
    for field, name in TYPOGRAPHY_TOKENS:
        if typo.get(field):
            out.append("%s%s: %s;" % (indent, _var(prefix, name), typo[field]))
    for field, name in TYPOGRAPHY_PX:
        if typo.get(field):
            out.append("%s%s: %dpx;" % (indent, _var(prefix, name), int(typo[field])))
    for field, name in TYPOGRAPHY_NUM:
        if typo.get(field):
            out.append("%s%s: %d;" % (indent, _var(prefix, name), int(typo[field])))
    metrics = theme.get("metrics") or {}
    for field, name in METRICS_PX:
        if metrics.get(field):
            out.append("%s%s: %dpx;" % (indent, _var(prefix, name), int(metrics[field])))
    return out


def to_css_vars(theme: dict, *, prefix: str = "brand", selector: str = ":root") -> str:
    """Render a Theme dict as a CSS custom-property stylesheet.

    Emits the light palette on `selector`, then the dark palette twice: under
    `prefers-color-scheme: dark` and under an explicit `[data-theme="dark"]`.
    Both are needed and neither is redundant -- the media query is what an OS
    dark-mode user gets with no interaction, and the attribute is what an
    in-product theme toggle sets. A stylesheet with only the first cannot be
    toggled; with only the second it ignores the system.

    A skin with no `dark` palette emits only the light block, which is the correct
    result for a single-mode brand rather than a silent duplicate.
    """
    light = theme.get("light") or {}
    dark = theme.get("dark") or {}

    name = theme.get("display_name") or theme.get("id") or "brand"
    lines = [
        "/* %s — generated by brando marklib.tokens. Do not edit by hand:" % name,
        " * this is a projection of the skin's Theme, and the skin is the source. */",
        "%s {" % selector,
    ]
    lines += _palette_block(light, prefix)
    lines += _shared_block(theme, prefix)
    lines.append("}")

    if dark:
        dark_lines = _palette_block(dark, prefix, indent="    ")
        lines += [
            "",
            "@media (prefers-color-scheme: dark) {",
            "  %s {" % selector,
            *dark_lines,
            "  }",
            "}",
            "",
            '%s[data-theme="dark"] {' % selector,
            *_palette_block(dark, prefix),
            "}",
        ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Theme JSON -> CSS custom properties")
    ap.add_argument("--theme_json", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--prefix", default="brand")
    ap.add_argument("--selector", default=":root")
    args = ap.parse_args(argv)

    with open(args.theme_json, encoding="utf-8") as fh:
        theme = json.load(fh)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(to_css_vars(theme, prefix=args.prefix, selector=args.selector))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
