#!/usr/bin/env python3
"""Compute where a `.brando` will be published, and how to pin it. STDLIB ONLY.

SPLIT ON PURPOSE: this half is hermetic and the network half is not. Everything a
consumer needs to pin a package — the content-addressed key, the URL, the SRI
integrity — is a pure function of the bytes, so it is a BUILD ARTIFACT that a
test can check. Only the `aws s3 cp` needs credentials, and that reads the plan
this writes.

The failure that motivates it: `rules_brand.from_url` requires `integrity`, and
computing an SRI hash by hand is the kind of step people skip. Skipping it is not
a small thing — a brand is what a company looks like, and an unpinned fetch means
a CDN object swap restyles every consumer at once, silently. So the pin is
generated with the artifact rather than derived by whoever happens to publish it.

WHY THE KEY EMBEDS THE HASH. Same convention as `aion/platform/tools/publish-brand.sh`,
which this is designed to sit beside: a key never changes meaning, so edges cache
it forever and no CloudFront invalidation is needed on publish. The mutable part
is a small index at a short TTL.

CLI: publish_plan.py --package P --base_url U [--prefix brando] [--version V]
                     --out_json J [--out_snippet S]
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import sys


def sri(digest: bytes) -> str:
    """Subresource Integrity, the form Bazel's `integrity =` attribute takes."""
    return "sha256-" + base64.b64encode(digest).decode("ascii")


def plan(package_path: str, base_url: str, prefix: str, brand: str, version: str) -> dict:
    with open(package_path, "rb") as fh:
        data = fh.read()
    digest = hashlib.sha256(data).digest()
    hexdigest = digest.hex()

    # The key carries the hash, so the URL is immutable. `version` is carried in
    # the plan but NOT in the key: two builds of the same version can differ (a
    # regenerated asset, a new brando), and a version-keyed URL would then have
    # two meanings — the exact ambiguity content addressing exists to remove.
    key = "%s/%s.%s.brando" % (prefix, brand, hexdigest[:16])

    return {
        "brand": brand,
        "version": version,
        "key": key,
        "url": "%s/%s" % (base_url.rstrip("/"), key),
        "integrity": sri(digest),
        "sha256": hexdigest,
        "size_bytes": len(data),
    }


_SNIPPET = '''# Wear the %(brand)s brand. Generated by brando's publish_plan — paste into MODULE.bazel.
bazel_dep(name = "rules_brand", version = "0.1.1")

brand = use_extension("@rules_brand//brand:extensions.bzl", "brand")
brand.from_url(
    name = "%(brand)s",
    urls = ["%(url)s"],
    integrity = "%(integrity)s",
)
use_repo(brand, "%(brand)s")
'''


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--package", required=True, help="the .brando to publish")
    ap.add_argument("--base_url", required=True, help="e.g. https://static.aion.savvifi.dev")
    ap.add_argument("--prefix", default="brando")
    ap.add_argument("--brand", default="", help="defaults to the package filename stem")
    ap.add_argument("--version", default="")
    ap.add_argument("--out_json", required=True)
    ap.add_argument("--out_snippet", default="")
    args = ap.parse_args(argv)

    brand = args.brand or os.path.basename(args.package).split(".")[0]
    result = plan(args.package, args.base_url, args.prefix, brand, args.version)

    with open(args.out_json, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, sort_keys=True)
        fh.write("\n")

    if args.out_snippet:
        with open(args.out_snippet, "w", encoding="utf-8") as fh:
            fh.write(_SNIPPET % result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
